name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: "Downstream ${{ matrix.package.repo }}/${{ matrix.package.group }}"
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1]
        package:
          - {user: SciML, repo: SciMLBase.jl, group: InterfaceII}
          - {user: SciML, repo: DiffEqBase.jl, group: InterfaceII}
          - {user: SciML, repo: LinearSolve.jl, group: InterfaceII}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: InterfaceII}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      julia-version: "${{ matrix.julia-version }}"
      julia-arch: "x64"
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
